### PR TITLE
{e} -> e, and {op e} -> (op e)

### PR DESCRIPTION
**Pull request by AlexKnauth**
There was a test that I had to change for this, so, did you have a specific reason for not doing this?

### CODE REVIEW

**Comment by AlexKnauth** [comment]
@takikawa what do you think about this?

**Comment by takikawa** [comment]
No specific reason, but the original behavior (putting in `nfx`) is what's described in the original sweet expressions document I think. The test suite is just taken from the original implementation.

Would it be better to just bind `nfx` to a macro that does this transformation?

**Comment by AlexKnauth** [comment]
In the video at about 04:47 here: http://readable.sourceforge.net
He says that a singe datum in a curly-list is that datum and two datums are those two datums in that order.

**Comment by takikawa** [comment]
Oh, sounds good then. Maybe the test suite was wrong or maybe I broke it at some point.

**Pull request merged**
